### ISSUE TITLE
ScrollablePositionedList has bounce effects and glitches

### ISSUE THREAD

**Issue by DamirDautov** [google/flutter.widgets#276]
## Problem description
ScrollablePositionedList has undesirable bounce effects

## Steps to reproduce
I made a [small repo](https://github.com/DamirDautov/scrollable_positioned_list_bug/) for reproducing bounce effect bug and also made there some [workaround](https://github.com/DamirDautov/scrollable_positioned_list_bug/blob/5b313ac800a2cc12eff5a4407e3ed03923fabde9/lib/scrollable_positioned_list/lib/src/viewport.dart#L250) that helped me see one strange thing.
So all in all here are the steps to reproduce:
1. Set alignment to 0.0
2. `jumpTo` last item in direct list
3. Code tries to position target item (last one) at desirable position-alignment
4. Leading items of list go above the visible part
5. Correction happens that causes `bounceEffect`

But the problem is, of course, appears not only for direct list when you `jumpTo` last item with alignment < 1.0.
How you can see in example repo it happens for items in the middle as well, and for reversed list too.

## Expected behavior
List doesn't bounce when you use `jumpTo` with alignment

## Actual behavior
Bounce effect appears

## Environment
Flutter 2.2.1, scrollable_positioned_list 0.1.12

## Additional details
1. This issue was described before [71](https://github.com/google/flutter.widgets/issues/71), [103](https://github.com/google/flutter.widgets/issues/103), [151](https://github.com/google/flutter.widgets/issues/151), [234](https://github.com/google/flutter.widgets/issues/234), [249](https://github.com/google/flutter.widgets/issues/249) and I believe first one was [38](https://github.com/google/flutter.widgets/issues/38). So the problem seems to exist for a long time, that's why I created this issue, like to summarize them all, and also there's [this googleDoc](https://docs.google.com/document/d/1ozIndwAbYcd96ktOX8LnsZ1L-K08q2XvdDD3G_ruEE8/edit#) with rework proposal that should really be considered.

2. Also I made a [small workaround](https://github.com/DamirDautov/scrollable_positioned_list_bug/blob/5b313ac800a2cc12eff5a4407e3ed03923fabde9/lib/scrollable_positioned_list/lib/src/viewport.dart#L250) in example repo, that doesn't allow overscroll at all which is not nice even though I'm using `ClampingScrollPhysics` in my project. But it showed me some glitch effect, that when you change the target item `leadingNegativeChild` has incorrect geometry value of scrollExtent in first frame, for me it's always 0.0, but in reality it isn't. Next frames have correct geometry values of `leadingNegativeChild`. So my workaround helps only when you always `jumpTo` one and only one item, otherwise it has glitchy effect.
So what I tried to point is that maybe someone can see further and understand what causes the problem with glitch or even maybe fix the whole bounce effect issue. Thanks

**Comment by ModWU** [comment]
Has the problem been solved? I had the same problem

**Comment by DamirDautov** [comment]
> Has the problem been solved? I had the same problem

Nothing I've seen about it. I believe that package is abandoned a bit :(

**Comment by ModWU** [comment]
Do you have a good solution？

**Comment by DamirDautov** [comment]
@ModWU Nope. Only small buggy workaround for very particular case https://github.com/DamirDautov/scrollable_positioned_list_bug/blob/5b313ac800a2cc12eff5a4407e3ed03923fabde9/lib/scrollable_positioned_list/lib/src/viewport.dart#L250

**Comment by ModWU** [comment]
I hope this problem can be fixed as soon as possible. I am using this plugin in my current project.

**Comment by ModWU** [comment]
> @ModWU Nope. Only small buggy workaround for very particular case https://github.com/DamirDautov/scrollable_positioned_list_bug/blob/5b313ac800a2cc12eff5a4407e3ed03923fabde9/lib/scrollable_positioned_list/lib/src/viewport.dart#L250

Hello, My current solution is to leave more space at the end, but this is not a good way, I don't have any other way!
![ezgif com-gif-maker](https://user-images.githubusercontent.com/16234264/127612030-06db7a45-39b6-4c91-b3c5-3d5168d3d0b7.gif)

**Comment by ModWU** [comment]
hello, I have fixed the bug!

https://user-images.githubusercontent.com/16234264/127652688-ab6b741e-33a4-486c-a563-a552b79b0333.mp4

**Comment by DamirDautov** [comment]
@wapchief https://github.com/DamirDautov/scrollable_positioned_list_bug/blob/main/lib/main.dart#L154 I have already used that behavior, but bug still exists, list still has bounce effect

**Comment by lamnguyen2169** [comment]
> > @ModWU Nope. Only small buggy workaround for very particular case https://github.com/DamirDautov/scrollable_positioned_list_bug/blob/5b313ac800a2cc12eff5a4407e3ed03923fabde9/lib/scrollable_positioned_list/lib/src/viewport.dart#L250
> 
> Hello, My current solution is to leave more space at the end, but this is not a good way, I don't have any other way! ![ezgif com-gif-maker](https://user-images.githubusercontent.com/16234264/127612030-06db7a45-39b6-4c91-b3c5-3d5168d3d0b7.gif)

I think you should create an PR for this issue to the authors. This bug is really disaster, I'm making the chat screen by using this package. Anytime new message is added, the list bounces so crazy.

**Comment by DamirDautov** [comment]
@lamnguyen2169, the thing is that there is nothing to pull, I don't have any fix, only small workaround for a very particular case, but it doesn't help even me in my project (it is also about chat by the way)
